# Generated by Django 4.2.10 on 2024-02-15 15:23

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=website.models.get_product_image
            ),
        ),
    ]
